# Kubernetes AI Conformance Checklist
# Notes: This checklist is based on the Kubernetes AI Conformance document.
# Participants should fill in the 'status', 'evidence', and 'notes' fields for each requirement.

metadata:
  kubernetesVersion: v1.34
  platformName: "CCE（Cloud Container Engine）"
  platformVersion: "1.34"
  vendorName: "Baidu Cloud"
  websiteUrl: "https://cloud.baidu.com/"
  documentationUrl: "https://cloud.baidu.com/doc/CCE/index.html"
  productLogoUrl: "https://bce.bdstatic.com/console/img/logo_en.svg"
  description: "Cloud Container Engine (CCE) is a highly scalable, high-performance container management service. It allows you to easily run applications on hosted cloud server instance clusters. With CCE, there's no need to install, operate, and scale cluster management infrastructure. You can start and stop Docker applications, check the complete status of the cluster, and access various cloud services with simple API calls. Containers can be deployed in your cluster based on your resource and availability requirements, meeting the specific needs of your service or application."
  contactEmailAddress: "yuliang06@baidu.com"

spec:
  accelerators:
    - id: dra_support
      description: "Support Dynamic Resource Allocation (DRA) APIs to enable more flexible and fine-grained resource requests beyond simple counts."
      level: MUST
      status: "Implemented"   # Implemented, Not Implemented, Partially Implemented, N/A
      evidence: 
      - "https://intl.cloud.baidu.com/en/doc/CCE/s/xmhddquk7" # URL or reference to documentation/test results
      notes: "DRA v1 APIs are enabled in 1.34 by default"    # Must provide a justification when status is N/A
  networking:
    - id: ai_inference
      description: "Support the Kubernetes Gateway API with an implementation for advanced traffic management for inference services, which enables capabilities like weighted traffic splitting, header-based routing (for OpenAI protocol headers), and optional integration with service meshes."
      level: MUST
      status: "Implemented"
      evidence: 
      - "https://intl.cloud.baidu.com/en/doc/CCE/s/kmhddqumv"
      notes: ""
  schedulingOrchestration:
    - id: gang_scheduling
      description: "The platform must allow for the installation and successful operation of at least one gang scheduling solution that ensures all-or-nothing scheduling for distributed AI workloads (e.g. Kueue, Volcano, etc.) To be conformant, the vendor must demonstrate that their platform can successfully run at least one such solution."
      level: MUST
      status: "Implemented"
      evidence: 
      - "https://intl.cloud.baidu.com/en/doc/CCE/s/Umhddquu8"
      notes: ""
    - id: cluster_autoscaling
      description: "If the platform provides a cluster autoscaler or an equivalent mechanism, it must be able to scale up/down node groups containing specific accelerator types based on pending pods requesting those accelerators."
      level: MUST
      status: "Implemented"
      evidence: 
      - "https://intl.cloud.baidu.com/en/doc/CCE/s/Fmhddqus0"
      notes: ""
    - id: pod_autoscaling
      description: "If the platform supports the HorizontalPodAutoscaler, it must function correctly for pods utilizing accelerators. This includes the ability to scale these Pods based on custom metrics relevant to AI/ML workloads."
      level: MUST
      status: "Implemented"
      evidence: 
      - "https://intl.cloud.baidu.com/en/doc/CCE/s/amhddquwk"
      notes: "Implemented"
  observability:
    - id: accelerator_metrics
      description: "For supported accelerator types, the platform must allow for the installation and successful operation of at least one accelerator metrics solution that exposes fine-grained performance metrics via a standardized, machine-readable metrics endpoint. This must include a core set of metrics for per-accelerator utilization and memory usage. Additionally, other relevant metrics such as temperature, power draw, and interconnect bandwidth should be exposed if the underlying hardware or virtualization layer makes them available. The list of metrics should align with emerging standards, such as OpenTelemetry metrics, to ensure interoperability. The platform may provide a managed solution, but this is not required for conformance."
      level: MUST
      status: "Implemented"
      evidence: 
      - "https://intl.cloud.baidu.com/en/doc/CCE/s/Ulps6uxwe-intl-en"
      notes: ""
    - id: ai_service_metrics
      description: "Provide a monitoring system capable of discovering and collecting metrics from workloads that expose them in a standard format (e.g. Prometheus exposition format). This ensures easy integration for collecting key metrics from common AI frameworks and servers."
      level: MUST
      status: "Implemented"
      evidence: 
      - "https://intl.cloud.baidu.com/en/doc/CCE/s/slps718vs-intl-en"
      notes: ""
  security:
    - id: secure_accelerator_access
      description: "Ensure that access to accelerators from within containers is properly isolated and mediated by the Kubernetes resource management framework (device plugin or DRA) and container runtime, preventing unauthorized access or interference between workloads."
      level: MUST
      status: "Implemented"
      evidence: 
      - "https://intl.cloud.baidu.com/en/doc/CCE/s/Lmhddquze"
      notes: ""
  operator:
    - id: robust_controller
      description: "The platform must prove that at least one complex AI operator with a CRD (e.g., Ray, Kubeflow) can be installed and functions reliably. This includes verifying that the operator's pods run correctly, its webhooks are operational, and its custom resources can be reconciled."
      level: MUST
      status: "Implemented"
      evidence: 
      - "https://intl.cloud.baidu.com/en/doc/CCE/s/Jmhddqupe"
      notes: ""