# Kubernetes AI Conformance Checklist
# Notes: This checklist is based on the Kubernetes AI Conformance document.
# Participants should fill in the 'status', 'evidence', and 'notes' fields for each requirement.

metadata:
  kubernetesVersion: v1.33
  platformName: CSK
  platformVersion: v1.33
  vendorName: "Chinaunicom Cloud"
  websiteUrl: https://www.cucloud.cn/product/csk.html
  documentationUrl: "https://support.cucloud.cn/document/127/581/900.html?id=900&arcid=1756" 
  productLogoUrl: https://github.com/c479096292/cucsk/blob/main/docs/en/docs/images/en-logo.png
  description: "Chinaunicom container service product based on Kubernetes. It provides high-performance and scalable container application management capabilities"
  contactEmailAddress: caibw5@chinaunicom.cn

spec:
  accelerators:
    - id: dra_support
      description: "Support Dynamic Resource Allocation (DRA) APIs to enable more flexible and fine-grained resource requests beyond simple counts."
      level: SHOULD
      status: "Implemented"   # Implemented, Not Implemented, Partially Implemented, N/A
      evidence: 
        - ""
      notes: "DRA APIs are disabled in 1.33 by default"  
  networking:
    - id: ai_inference
      description: "Support the Kubernetes Gateway API with an implementation for advanced traffic management for inference services, which enables capabilities like weighted traffic splitting, header-based routing (for OpenAI protocol headers), and optional integration with service meshes."
      level: MUST
      status: "Implemented"
      evidence:
        - https://support.cucloud.cn/document/127/581/2541.html?id=2541&arcid=5492 
      notes: ""
  schedulingOrchestration:
    - id: gang_scheduling
      description: "The platform must allow for the installation and successful operation of at least one gang scheduling solution that ensures all-or-nothing scheduling for distributed AI workloads (e.g. Kueue, Volcano, etc.) To be conformant, the vendor must demonstrate that their platform can successfully run at least one such solution."
      level: MUST
      status: "Implemented"
      evidence:
        - https://support.cucloud.cn/document/127/581/2541.html?id=2541&arcid=5352 
      notes: ""
    - id: cluster_autoscaling
      description: "If the platform provides a cluster autoscaler or an equivalent mechanism, it must be able to scale up/down node groups containing specific accelerator types based on pending pods requesting those accelerators."
      level: MUST
      status: "Implemented"
      evidence:
        - https://support.cucloud.cn/document/127/581/2541.html?id=2541&arcid=5485 
      notes: "The platform does not provide an autoscaler. It can be used in and out of environments where autoscaling it possible. The platform is tested to work with Kubernetes autoscaler."
    - id: pod_autoscaling
      description: "If the platform supports the HorizontalPodAutoscaler, it must function correctly for pods utilizing accelerators. This includes the ability to scale these Pods based on custom metrics relevant to AI/ML workloads."
      level: MUST
      status: "Implemented"
      evidence:
        - https://support.cucloud.cn/document/127/581/2541.html?id=2541&arcid=5486 
      notes: ""
  observability:
    - id: accelerator_metrics
      description: "For supported accelerator types, the platform must allow for the installation and successful operation of at least one accelerator metrics solution that exposes fine-grained performance metrics via a standardized, machine-readable metrics endpoint. This must include a core set of metrics for per-accelerator utilization and memory usage. Additionally, other relevant metrics such as temperature, power draw, and interconnect bandwidth should be exposed if the underlying hardware or virtualization layer makes them available. The list of metrics should align with emerging standards, such as OpenTelemetry metrics, to ensure interoperability. The platform may provide a managed solution, but this is not required for conformance."
      level: MUST
      status: "Implemented"
      evidence:
        - https://support.cucloud.cn/document/127/581/2541.html?id=2541&arcid=5487
      notes: ""
    - id: ai_service_metrics
      description: "Provide a monitoring system capable of discovering and collecting metrics from workloads that expose them in a standard format (e.g. Prometheus exposition format). This ensures easy integration for collecting key metrics from common AI frameworks and servers."
      level: MUST
      status: "Implemented"
      evidence:
        - https://support.cucloud.cn/document/127/581/2541.html?id=2541&arcid=6052 
      notes: ""
  security:
    - id: secure_accelerator_access
      description: "Ensure that access to accelerators from within containers is properly isolated and mediated by the Kubernetes resource management framework (device plugin or DRA) and container runtime, preventing unauthorized access or interference between workloads."
      level: MUST
      status: "Implemented"
      evidence:
        - https://support.cucloud.cn/document/127/581/2541.html?id=2541&arcid=5489 
      notes: ""
  operator:
    - id: robust_controller
      description: "The platform must prove that at least one complex AI operator with a CRD (e.g., Ray, Kubeflow) can be installed and functions reliably. This includes verifying that the operator's pods run correctly, its webhooks are operational, and its custom resources can be reconciled."
      level: MUST
      status: "Implemented"
      evidence:
        - https://support.cucloud.cn/document/127/581/2541.html?id=2541&arcid=5490 
      notes: ""
